//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMTransporte.ServicioExternoRegionYComunas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegionTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RegionTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMTransporte.ServicioExternoRegionYComunas.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UMTransporte.ServicioExternoRegionYComunas.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComunaTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ComunaTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMTransporte.ServicioExternoRegionYComunas.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Auxiliar1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Auxiliar2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Auxiliar3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UMTransporte.ServicioExternoRegionYComunas.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Auxiliar1 {
            get {
                return this.Auxiliar1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Auxiliar1Field, value) != true)) {
                    this.Auxiliar1Field = value;
                    this.RaisePropertyChanged("Auxiliar1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Auxiliar2 {
            get {
                return this.Auxiliar2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Auxiliar2Field, value) != true)) {
                    this.Auxiliar2Field = value;
                    this.RaisePropertyChanged("Auxiliar2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Auxiliar3 {
            get {
                return this.Auxiliar3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Auxiliar3Field, value) != true)) {
                    this.Auxiliar3Field = value;
                    this.RaisePropertyChanged("Auxiliar3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Iata {
            get {
                return this.IataField;
            }
            set {
                if ((object.ReferenceEquals(this.IataField, value) != true)) {
                    this.IataField = value;
                    this.RaisePropertyChanged("Iata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NombreComuna {
            get {
                return this.NombreComunaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComunaField, value) != true)) {
                    this.NombreComunaField = value;
                    this.RaisePropertyChanged("NombreComuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap")]
    public interface ServicioExternoRegionYComunasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarTodasLasRegiones", ReplyAction="*")]
        UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesResponse listarTodasLasRegiones(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarTodasLasRegiones", ReplyAction="*")]
        System.Threading.Tasks.Task<UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesResponse> listarTodasLasRegionesAsync(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarComunasSegunRegion", ReplyAction="*")]
        UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionResponse listarComunasSegunRegion(UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarComunasSegunRegion", ReplyAction="*")]
        System.Threading.Tasks.Task<UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionResponse> listarComunasSegunRegionAsync(UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarTodasLasComunas", ReplyAction="*")]
        UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasResponse listarTodasLasComunas(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarTodasLasComunas", ReplyAction="*")]
        System.Threading.Tasks.Task<UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasResponse> listarTodasLasComunasAsync(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarTodasLasRegionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarTodasLasRegiones", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequestBody Body;
        
        public listarTodasLasRegionesRequest() {
        }
        
        public listarTodasLasRegionesRequest(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarTodasLasRegionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public listarTodasLasRegionesRequestBody() {
        }
        
        public listarTodasLasRegionesRequestBody(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarTodasLasRegionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarTodasLasRegionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesResponseBody Body;
        
        public listarTodasLasRegionesResponse() {
        }
        
        public listarTodasLasRegionesResponse(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarTodasLasRegionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UMTransporte.ServicioExternoRegionYComunas.RegionTO[] listarTodasLasRegionesResult;
        
        public listarTodasLasRegionesResponseBody() {
        }
        
        public listarTodasLasRegionesResponseBody(UMTransporte.ServicioExternoRegionYComunas.RegionTO[] listarTodasLasRegionesResult) {
            this.listarTodasLasRegionesResult = listarTodasLasRegionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarComunasSegunRegionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarComunasSegunRegion", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequestBody Body;
        
        public listarComunasSegunRegionRequest() {
        }
        
        public listarComunasSegunRegionRequest(UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarComunasSegunRegionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codigoRegion;
        
        public listarComunasSegunRegionRequestBody() {
        }
        
        public listarComunasSegunRegionRequestBody(string usuario, string contrasena, string codigoRegion) {
            this.usuario = usuario;
            this.contrasena = contrasena;
            this.codigoRegion = codigoRegion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarComunasSegunRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarComunasSegunRegionResponse", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionResponseBody Body;
        
        public listarComunasSegunRegionResponse() {
        }
        
        public listarComunasSegunRegionResponse(UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarComunasSegunRegionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UMTransporte.ServicioExternoRegionYComunas.ComunaTO[] listarComunasSegunRegionResult;
        
        public listarComunasSegunRegionResponseBody() {
        }
        
        public listarComunasSegunRegionResponseBody(UMTransporte.ServicioExternoRegionYComunas.ComunaTO[] listarComunasSegunRegionResult) {
            this.listarComunasSegunRegionResult = listarComunasSegunRegionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarTodasLasComunasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarTodasLasComunas", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequestBody Body;
        
        public listarTodasLasComunasRequest() {
        }
        
        public listarTodasLasComunasRequest(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarTodasLasComunasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public listarTodasLasComunasRequestBody() {
        }
        
        public listarTodasLasComunasRequestBody(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarTodasLasComunasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarTodasLasComunasResponse", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasResponseBody Body;
        
        public listarTodasLasComunasResponse() {
        }
        
        public listarTodasLasComunasResponse(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarTodasLasComunasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UMTransporte.ServicioExternoRegionYComunas.ComunaTO[] listarTodasLasComunasResult;
        
        public listarTodasLasComunasResponseBody() {
        }
        
        public listarTodasLasComunasResponseBody(UMTransporte.ServicioExternoRegionYComunas.ComunaTO[] listarTodasLasComunasResult) {
            this.listarTodasLasComunasResult = listarTodasLasComunasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioExternoRegionYComunasSoapChannel : UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioExternoRegionYComunasSoapClient : System.ServiceModel.ClientBase<UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap>, UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap {
        
        public ServicioExternoRegionYComunasSoapClient() {
        }
        
        public ServicioExternoRegionYComunasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioExternoRegionYComunasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioExternoRegionYComunasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioExternoRegionYComunasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesResponse UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap.listarTodasLasRegiones(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequest request) {
            return base.Channel.listarTodasLasRegiones(request);
        }
        
        public UMTransporte.ServicioExternoRegionYComunas.RegionTO[] listarTodasLasRegiones(string usuario, string contrasena) {
            UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequest inValue = new UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequest();
            inValue.Body = new UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesResponse retVal = ((UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap)(this)).listarTodasLasRegiones(inValue);
            return retVal.Body.listarTodasLasRegionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesResponse> UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap.listarTodasLasRegionesAsync(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequest request) {
            return base.Channel.listarTodasLasRegionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesResponse> listarTodasLasRegionesAsync(string usuario, string contrasena) {
            UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequest inValue = new UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequest();
            inValue.Body = new UMTransporte.ServicioExternoRegionYComunas.listarTodasLasRegionesRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap)(this)).listarTodasLasRegionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionResponse UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap.listarComunasSegunRegion(UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequest request) {
            return base.Channel.listarComunasSegunRegion(request);
        }
        
        public UMTransporte.ServicioExternoRegionYComunas.ComunaTO[] listarComunasSegunRegion(string usuario, string contrasena, string codigoRegion) {
            UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequest inValue = new UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequest();
            inValue.Body = new UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            inValue.Body.codigoRegion = codigoRegion;
            UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionResponse retVal = ((UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap)(this)).listarComunasSegunRegion(inValue);
            return retVal.Body.listarComunasSegunRegionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionResponse> UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap.listarComunasSegunRegionAsync(UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequest request) {
            return base.Channel.listarComunasSegunRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionResponse> listarComunasSegunRegionAsync(string usuario, string contrasena, string codigoRegion) {
            UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequest inValue = new UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequest();
            inValue.Body = new UMTransporte.ServicioExternoRegionYComunas.listarComunasSegunRegionRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            inValue.Body.codigoRegion = codigoRegion;
            return ((UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap)(this)).listarComunasSegunRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasResponse UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap.listarTodasLasComunas(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequest request) {
            return base.Channel.listarTodasLasComunas(request);
        }
        
        public UMTransporte.ServicioExternoRegionYComunas.ComunaTO[] listarTodasLasComunas(string usuario, string contrasena) {
            UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequest inValue = new UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequest();
            inValue.Body = new UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasResponse retVal = ((UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap)(this)).listarTodasLasComunas(inValue);
            return retVal.Body.listarTodasLasComunasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasResponse> UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap.listarTodasLasComunasAsync(UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequest request) {
            return base.Channel.listarTodasLasComunasAsync(request);
        }
        
        public System.Threading.Tasks.Task<UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasResponse> listarTodasLasComunasAsync(string usuario, string contrasena) {
            UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequest inValue = new UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequest();
            inValue.Body = new UMTransporte.ServicioExternoRegionYComunas.listarTodasLasComunasRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((UMTransporte.ServicioExternoRegionYComunas.ServicioExternoRegionYComunasSoap)(this)).listarTodasLasComunasAsync(inValue);
        }
    }
}
