//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMTransporte.ExternoTarificacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductoTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodigoServicio {
            get {
                return this.CodigoServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoServicioField, value) != true)) {
                    this.CodigoServicioField = value;
                    this.RaisePropertyChanged("CodigoServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoberturaTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CoberturaTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalRemitenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComunaDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComunaRemitenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImporteReembolsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImporteValorAseguradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KilosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTotalPiezaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisRemitenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPortesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VolumenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodigoPostalDestinatario {
            get {
                return this.CodigoPostalDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalDestinatarioField, value) != true)) {
                    this.CodigoPostalDestinatarioField = value;
                    this.RaisePropertyChanged("CodigoPostalDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodigoPostalRemitente {
            get {
                return this.CodigoPostalRemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalRemitenteField, value) != true)) {
                    this.CodigoPostalRemitenteField = value;
                    this.RaisePropertyChanged("CodigoPostalRemitente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ComunaDestino {
            get {
                return this.ComunaDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComunaDestinoField, value) != true)) {
                    this.ComunaDestinoField = value;
                    this.RaisePropertyChanged("ComunaDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ComunaRemitente {
            get {
                return this.ComunaRemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.ComunaRemitenteField, value) != true)) {
                    this.ComunaRemitenteField = value;
                    this.RaisePropertyChanged("ComunaRemitente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ImporteReembolso {
            get {
                return this.ImporteReembolsoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImporteReembolsoField, value) != true)) {
                    this.ImporteReembolsoField = value;
                    this.RaisePropertyChanged("ImporteReembolso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ImporteValorAsegurado {
            get {
                return this.ImporteValorAseguradoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImporteValorAseguradoField, value) != true)) {
                    this.ImporteValorAseguradoField = value;
                    this.RaisePropertyChanged("ImporteValorAsegurado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Kilos {
            get {
                return this.KilosField;
            }
            set {
                if ((object.ReferenceEquals(this.KilosField, value) != true)) {
                    this.KilosField = value;
                    this.RaisePropertyChanged("Kilos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string NumeroTotalPieza {
            get {
                return this.NumeroTotalPiezaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTotalPiezaField, value) != true)) {
                    this.NumeroTotalPiezaField = value;
                    this.RaisePropertyChanged("NumeroTotalPieza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string PaisDestinatario {
            get {
                return this.PaisDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisDestinatarioField, value) != true)) {
                    this.PaisDestinatarioField = value;
                    this.RaisePropertyChanged("PaisDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string PaisRemitente {
            get {
                return this.PaisRemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisRemitenteField, value) != true)) {
                    this.PaisRemitenteField = value;
                    this.RaisePropertyChanged("PaisRemitente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TipoPortes {
            get {
                return this.TipoPortesField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPortesField, value) != true)) {
                    this.TipoPortesField = value;
                    this.RaisePropertyChanged("TipoPortes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Volumen {
            get {
                return this.VolumenField;
            }
            set {
                if ((object.ReferenceEquals(this.VolumenField, value) != true)) {
                    this.VolumenField = value;
                    this.RaisePropertyChanged("Volumen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ServicioTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMTransporte.ExternoTarificacion.ConceptoTasacionTO[] ConceptosTasacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMTransporte.ExternoTarificacion.TotalTasacionTO TotalTasacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodigoServicio {
            get {
                return this.CodigoServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoServicioField, value) != true)) {
                    this.CodigoServicioField = value;
                    this.RaisePropertyChanged("CodigoServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public UMTransporte.ExternoTarificacion.ConceptoTasacionTO[] ConceptosTasacion {
            get {
                return this.ConceptosTasacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptosTasacionField, value) != true)) {
                    this.ConceptosTasacionField = value;
                    this.RaisePropertyChanged("ConceptosTasacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public UMTransporte.ExternoTarificacion.TotalTasacionTO TotalTasacion {
            get {
                return this.TotalTasacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalTasacionField, value) != true)) {
                    this.TotalTasacionField = value;
                    this.RaisePropertyChanged("TotalTasacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalTasacionTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TotalTasacionTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConceptoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ConceptoTotal {
            get {
                return this.ConceptoTotalField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptoTotalField, value) != true)) {
                    this.ConceptoTotalField = value;
                    this.RaisePropertyChanged("ConceptoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Total {
            get {
                return this.TotalField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalField, value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConceptoTasacionTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ConceptoTasacionTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConceptoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImpuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Base {
            get {
                return this.BaseField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseField, value) != true)) {
                    this.BaseField = value;
                    this.RaisePropertyChanged("Base");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Concepto {
            get {
                return this.ConceptoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptoField, value) != true)) {
                    this.ConceptoField = value;
                    this.RaisePropertyChanged("Concepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Impuesto {
            get {
                return this.ImpuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpuestoField, value) != true)) {
                    this.ImpuestoField = value;
                    this.RaisePropertyChanged("Impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Portes {
            get {
                return this.PortesField;
            }
            set {
                if ((object.ReferenceEquals(this.PortesField, value) != true)) {
                    this.PortesField = value;
                    this.RaisePropertyChanged("Portes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoberturaProductoTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CoberturaProductoTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalRemitenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComunaDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComunaRemitenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImporteReembolsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImporteValorAseguradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KilosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTotalPiezaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisRemitenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPortesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VolumenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public UMTransporte.ExternoTarificacion.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodigoPostalDestinatario {
            get {
                return this.CodigoPostalDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalDestinatarioField, value) != true)) {
                    this.CodigoPostalDestinatarioField = value;
                    this.RaisePropertyChanged("CodigoPostalDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodigoPostalRemitente {
            get {
                return this.CodigoPostalRemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalRemitenteField, value) != true)) {
                    this.CodigoPostalRemitenteField = value;
                    this.RaisePropertyChanged("CodigoPostalRemitente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CodigoServicio {
            get {
                return this.CodigoServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoServicioField, value) != true)) {
                    this.CodigoServicioField = value;
                    this.RaisePropertyChanged("CodigoServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ComunaDestino {
            get {
                return this.ComunaDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComunaDestinoField, value) != true)) {
                    this.ComunaDestinoField = value;
                    this.RaisePropertyChanged("ComunaDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ComunaRemitente {
            get {
                return this.ComunaRemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.ComunaRemitenteField, value) != true)) {
                    this.ComunaRemitenteField = value;
                    this.RaisePropertyChanged("ComunaRemitente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ImporteReembolso {
            get {
                return this.ImporteReembolsoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImporteReembolsoField, value) != true)) {
                    this.ImporteReembolsoField = value;
                    this.RaisePropertyChanged("ImporteReembolso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ImporteValorAsegurado {
            get {
                return this.ImporteValorAseguradoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImporteValorAseguradoField, value) != true)) {
                    this.ImporteValorAseguradoField = value;
                    this.RaisePropertyChanged("ImporteValorAsegurado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Kilos {
            get {
                return this.KilosField;
            }
            set {
                if ((object.ReferenceEquals(this.KilosField, value) != true)) {
                    this.KilosField = value;
                    this.RaisePropertyChanged("Kilos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string NumeroTotalPieza {
            get {
                return this.NumeroTotalPiezaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTotalPiezaField, value) != true)) {
                    this.NumeroTotalPiezaField = value;
                    this.RaisePropertyChanged("NumeroTotalPieza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string PaisDestinatario {
            get {
                return this.PaisDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisDestinatarioField, value) != true)) {
                    this.PaisDestinatarioField = value;
                    this.RaisePropertyChanged("PaisDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string PaisRemitente {
            get {
                return this.PaisRemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisRemitenteField, value) != true)) {
                    this.PaisRemitenteField = value;
                    this.RaisePropertyChanged("PaisRemitente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TipoPortes {
            get {
                return this.TipoPortesField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPortesField, value) != true)) {
                    this.TipoPortesField = value;
                    this.RaisePropertyChanged("TipoPortes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Volumen {
            get {
                return this.VolumenField;
            }
            set {
                if ((object.ReferenceEquals(this.VolumenField, value) != true)) {
                    this.VolumenField = value;
                    this.RaisePropertyChanged("Volumen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExternoTarificacion.ExternoTarificacionSoap")]
    public interface ExternoTarificacionSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaProductosPorCliente", ReplyAction="*")]
        UMTransporte.ExternoTarificacion.consultaProductosPorClienteResponse consultaProductosPorCliente(UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaProductosPorCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<UMTransporte.ExternoTarificacion.consultaProductosPorClienteResponse> consultaProductosPorClienteAsync(UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaCobertura", ReplyAction="*")]
        UMTransporte.ExternoTarificacion.consultaCoberturaResponse consultaCobertura(UMTransporte.ExternoTarificacion.consultaCoberturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaCobertura", ReplyAction="*")]
        System.Threading.Tasks.Task<UMTransporte.ExternoTarificacion.consultaCoberturaResponse> consultaCoberturaAsync(UMTransporte.ExternoTarificacion.consultaCoberturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaCoberturaPorProducto", ReplyAction="*")]
        UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoResponse consultaCoberturaPorProducto(UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaCoberturaPorProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoResponse> consultaCoberturaPorProductoAsync(UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaProductosPorClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaProductosPorCliente", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequestBody Body;
        
        public consultaProductosPorClienteRequest() {
        }
        
        public consultaProductosPorClienteRequest(UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaProductosPorClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public consultaProductosPorClienteRequestBody() {
        }
        
        public consultaProductosPorClienteRequestBody(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaProductosPorClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaProductosPorClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ExternoTarificacion.consultaProductosPorClienteResponseBody Body;
        
        public consultaProductosPorClienteResponse() {
        }
        
        public consultaProductosPorClienteResponse(UMTransporte.ExternoTarificacion.consultaProductosPorClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaProductosPorClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UMTransporte.ExternoTarificacion.ProductoTO[] consultaProductosPorClienteResult;
        
        public consultaProductosPorClienteResponseBody() {
        }
        
        public consultaProductosPorClienteResponseBody(UMTransporte.ExternoTarificacion.ProductoTO[] consultaProductosPorClienteResult) {
            this.consultaProductosPorClienteResult = consultaProductosPorClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCoberturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaCobertura", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ExternoTarificacion.consultaCoberturaRequestBody Body;
        
        public consultaCoberturaRequest() {
        }
        
        public consultaCoberturaRequest(UMTransporte.ExternoTarificacion.consultaCoberturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaCoberturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public UMTransporte.ExternoTarificacion.CoberturaTO consultaCobertura;
        
        public consultaCoberturaRequestBody() {
        }
        
        public consultaCoberturaRequestBody(string usuario, string contrasena, UMTransporte.ExternoTarificacion.CoberturaTO consultaCobertura) {
            this.usuario = usuario;
            this.contrasena = contrasena;
            this.consultaCobertura = consultaCobertura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCoberturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaCoberturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ExternoTarificacion.consultaCoberturaResponseBody Body;
        
        public consultaCoberturaResponse() {
        }
        
        public consultaCoberturaResponse(UMTransporte.ExternoTarificacion.consultaCoberturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaCoberturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UMTransporte.ExternoTarificacion.ServicioTO[] consultaCoberturaResult;
        
        public consultaCoberturaResponseBody() {
        }
        
        public consultaCoberturaResponseBody(UMTransporte.ExternoTarificacion.ServicioTO[] consultaCoberturaResult) {
            this.consultaCoberturaResult = consultaCoberturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCoberturaPorProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaCoberturaPorProducto", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequestBody Body;
        
        public consultaCoberturaPorProductoRequest() {
        }
        
        public consultaCoberturaPorProductoRequest(UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaCoberturaPorProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public UMTransporte.ExternoTarificacion.CoberturaProductoTO consultaCobertura;
        
        public consultaCoberturaPorProductoRequestBody() {
        }
        
        public consultaCoberturaPorProductoRequestBody(string usuario, string contrasena, UMTransporte.ExternoTarificacion.CoberturaProductoTO consultaCobertura) {
            this.usuario = usuario;
            this.contrasena = contrasena;
            this.consultaCobertura = consultaCobertura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCoberturaPorProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaCoberturaPorProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoResponseBody Body;
        
        public consultaCoberturaPorProductoResponse() {
        }
        
        public consultaCoberturaPorProductoResponse(UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaCoberturaPorProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UMTransporte.ExternoTarificacion.ServicioTO consultaCoberturaPorProductoResult;
        
        public consultaCoberturaPorProductoResponseBody() {
        }
        
        public consultaCoberturaPorProductoResponseBody(UMTransporte.ExternoTarificacion.ServicioTO consultaCoberturaPorProductoResult) {
            this.consultaCoberturaPorProductoResult = consultaCoberturaPorProductoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExternoTarificacionSoapChannel : UMTransporte.ExternoTarificacion.ExternoTarificacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExternoTarificacionSoapClient : System.ServiceModel.ClientBase<UMTransporte.ExternoTarificacion.ExternoTarificacionSoap>, UMTransporte.ExternoTarificacion.ExternoTarificacionSoap {
        
        public ExternoTarificacionSoapClient() {
        }
        
        public ExternoTarificacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExternoTarificacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternoTarificacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternoTarificacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UMTransporte.ExternoTarificacion.consultaProductosPorClienteResponse UMTransporte.ExternoTarificacion.ExternoTarificacionSoap.consultaProductosPorCliente(UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequest request) {
            return base.Channel.consultaProductosPorCliente(request);
        }
        
        public UMTransporte.ExternoTarificacion.ProductoTO[] consultaProductosPorCliente(string usuario, string contrasena) {
            UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequest inValue = new UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequest();
            inValue.Body = new UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            UMTransporte.ExternoTarificacion.consultaProductosPorClienteResponse retVal = ((UMTransporte.ExternoTarificacion.ExternoTarificacionSoap)(this)).consultaProductosPorCliente(inValue);
            return retVal.Body.consultaProductosPorClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UMTransporte.ExternoTarificacion.consultaProductosPorClienteResponse> UMTransporte.ExternoTarificacion.ExternoTarificacionSoap.consultaProductosPorClienteAsync(UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequest request) {
            return base.Channel.consultaProductosPorClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<UMTransporte.ExternoTarificacion.consultaProductosPorClienteResponse> consultaProductosPorClienteAsync(string usuario, string contrasena) {
            UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequest inValue = new UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequest();
            inValue.Body = new UMTransporte.ExternoTarificacion.consultaProductosPorClienteRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((UMTransporte.ExternoTarificacion.ExternoTarificacionSoap)(this)).consultaProductosPorClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UMTransporte.ExternoTarificacion.consultaCoberturaResponse UMTransporte.ExternoTarificacion.ExternoTarificacionSoap.consultaCobertura(UMTransporte.ExternoTarificacion.consultaCoberturaRequest request) {
            return base.Channel.consultaCobertura(request);
        }
        
        public UMTransporte.ExternoTarificacion.ServicioTO[] consultaCobertura(string usuario, string contrasena, UMTransporte.ExternoTarificacion.CoberturaTO consultaCobertura1) {
            UMTransporte.ExternoTarificacion.consultaCoberturaRequest inValue = new UMTransporte.ExternoTarificacion.consultaCoberturaRequest();
            inValue.Body = new UMTransporte.ExternoTarificacion.consultaCoberturaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            inValue.Body.consultaCobertura = consultaCobertura1;
            UMTransporte.ExternoTarificacion.consultaCoberturaResponse retVal = ((UMTransporte.ExternoTarificacion.ExternoTarificacionSoap)(this)).consultaCobertura(inValue);
            return retVal.Body.consultaCoberturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UMTransporte.ExternoTarificacion.consultaCoberturaResponse> UMTransporte.ExternoTarificacion.ExternoTarificacionSoap.consultaCoberturaAsync(UMTransporte.ExternoTarificacion.consultaCoberturaRequest request) {
            return base.Channel.consultaCoberturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UMTransporte.ExternoTarificacion.consultaCoberturaResponse> consultaCoberturaAsync(string usuario, string contrasena, UMTransporte.ExternoTarificacion.CoberturaTO consultaCobertura) {
            UMTransporte.ExternoTarificacion.consultaCoberturaRequest inValue = new UMTransporte.ExternoTarificacion.consultaCoberturaRequest();
            inValue.Body = new UMTransporte.ExternoTarificacion.consultaCoberturaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            inValue.Body.consultaCobertura = consultaCobertura;
            return ((UMTransporte.ExternoTarificacion.ExternoTarificacionSoap)(this)).consultaCoberturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoResponse UMTransporte.ExternoTarificacion.ExternoTarificacionSoap.consultaCoberturaPorProducto(UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequest request) {
            return base.Channel.consultaCoberturaPorProducto(request);
        }
        
        public UMTransporte.ExternoTarificacion.ServicioTO consultaCoberturaPorProducto(string usuario, string contrasena, UMTransporte.ExternoTarificacion.CoberturaProductoTO consultaCobertura) {
            UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequest inValue = new UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequest();
            inValue.Body = new UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            inValue.Body.consultaCobertura = consultaCobertura;
            UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoResponse retVal = ((UMTransporte.ExternoTarificacion.ExternoTarificacionSoap)(this)).consultaCoberturaPorProducto(inValue);
            return retVal.Body.consultaCoberturaPorProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoResponse> UMTransporte.ExternoTarificacion.ExternoTarificacionSoap.consultaCoberturaPorProductoAsync(UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequest request) {
            return base.Channel.consultaCoberturaPorProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoResponse> consultaCoberturaPorProductoAsync(string usuario, string contrasena, UMTransporte.ExternoTarificacion.CoberturaProductoTO consultaCobertura) {
            UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequest inValue = new UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequest();
            inValue.Body = new UMTransporte.ExternoTarificacion.consultaCoberturaPorProductoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            inValue.Body.consultaCobertura = consultaCobertura;
            return ((UMTransporte.ExternoTarificacion.ExternoTarificacionSoap)(this)).consultaCoberturaPorProductoAsync(inValue);
        }
    }
}
